class FixListData {
  String mno;
  String deviceType;
  String imei;
  String describe;
  String linkman;
  String linkMobile;
  String problemImg;
  String archivesId;
  String remark;
  String state;
  String owner;
  String cost;
  String reporter;
  String allocator;
  String negotiateTime;
  String allocateTime;
  String called;
  String toCode;
  String manager;
  String faultType;
  String address;
  num fixId;
  String flow;
  String lastState;
  String newestMaintain;
  String repairType;
  String expenseInvoice;
  String maintains;
  String flows;
  String malfuncCallback;
  String device;
  bool canOperated;
  int id;
  int requireTime;
  int type;
  int allocation;
  num reportTime;

  FixListData({this.mno, this.deviceType, this.imei, this.describe, this.linkman, this.linkMobile, this.problemImg, this.archivesId, this.remark, this.state, this.owner, this.cost, this.reporter, this.allocator, this.negotiateTime, this.allocateTime, this.called, this.toCode, this.manager, this.faultType, this.address, this.fixId, this.flow, this.lastState, this.newestMaintain, this.repairType, this.expenseInvoice, this.maintains, this.flows, this.malfuncCallback, this.device, this.canOperated, this.id, this.requireTime, this.type, this.allocation, this.reportTime});

  FixListData.fromJson(Map<String, dynamic> json) {    
    this.mno = json['mno'];
    this.deviceType = json['deviceType'];
    this.imei = json['imei'];
    this.describe = json['describe'];
    this.linkman = json['linkman'];
    this.linkMobile = json['linkMobile'];
    this.problemImg = json['problemImg'];
    this.archivesId = json['archivesId'];
    this.remark = json['remark'];
    this.state = json['state'];
    this.owner = json['owner'];
    this.cost = json['cost'];
    this.reporter = json['reporter'];
    this.allocator = json['allocator'];
    this.negotiateTime = json['negotiateTime'];
    this.allocateTime = json['allocateTime'];
    this.called = json['called'];
    this.toCode = json['toCode'];
    this.manager = json['manager'];
    this.faultType = json['faultType'];
    this.address = json['address'];
    this.fixId = json['fixId'];
    this.flow = json['flow'];
    this.lastState = json['lastState'];
    this.newestMaintain = json['newestMaintain'];
    this.repairType = json['repairType'];
    this.expenseInvoice = json['expenseInvoice'];
    this.maintains = json['maintains'];
    this.flows = json['flows'];
    this.malfuncCallback = json['malfuncCallback'];
    this.device = json['device'];
    this.canOperated = json['canOperated'];
    this.id = json['id'];
    this.requireTime = json['requireTime'];
    this.type = json['type'];
    this.allocation = json['allocation'];
    this.reportTime = json['reportTime'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['mno'] = this.mno;
    data['deviceType'] = this.deviceType;
    data['imei'] = this.imei;
    data['describe'] = this.describe;
    data['linkman'] = this.linkman;
    data['linkMobile'] = this.linkMobile;
    data['problemImg'] = this.problemImg;
    data['archivesId'] = this.archivesId;
    data['remark'] = this.remark;
    data['state'] = this.state;
    data['owner'] = this.owner;
    data['cost'] = this.cost;
    data['reporter'] = this.reporter;
    data['allocator'] = this.allocator;
    data['negotiateTime'] = this.negotiateTime;
    data['allocateTime'] = this.allocateTime;
    data['called'] = this.called;
    data['toCode'] = this.toCode;
    data['manager'] = this.manager;
    data['faultType'] = this.faultType;
    data['address'] = this.address;
    data['fixId'] = this.fixId;
    data['flow'] = this.flow;
    data['lastState'] = this.lastState;
    data['newestMaintain'] = this.newestMaintain;
    data['repairType'] = this.repairType;
    data['expenseInvoice'] = this.expenseInvoice;
    data['maintains'] = this.maintains;
    data['flows'] = this.flows;
    data['malfuncCallback'] = this.malfuncCallback;
    data['device'] = this.device;
    data['canOperated'] = this.canOperated;
    data['id'] = this.id;
    data['requireTime'] = this.requireTime;
    data['type'] = this.type;
    data['allocation'] = this.allocation;
    data['reportTime'] = this.reportTime;
    return data;
  }

}
